# Generated by Django 5.2 on 2025-05-07 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0004_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('Occasions', 'Occasions'), ('Parties', 'Parties'), ('Functions', 'Functions')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
