# Generated by Django 5.2 on 2025-05-09 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0007_remove_booking_booking_date_remove_booking_cus_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='payment_method',
            field=models.CharField(choices=[('Credit Card', 'Credit Card'), ('PayPal', 'PayPal'), ('Cash', 'Cash'), ('Bank Transfer', 'Bank Transfer')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='booking',
            name='payment_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
