# Generated by Django 5.2 on 2025-05-09 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0008_booking_payment_method_booking_payment_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='payment_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
