# Generated by Django 5.2 on 2025-05-09 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0010_alter_booking_payment_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='payment_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
